### ISSUE TITLE
Image not generating, syntax error

### ISSUE THREAD

**Issue by shreddedbacon** [cloudfoundry-community/bosh-deployment-visualizer#1]
Getting the following when opening the image
![cf](https://user-images.githubusercontent.com/9973880/51947322-8bb3c280-2478-11e9-8e65-9185027634d5.png)

Ubuntu 16.04
```
PlantUML Version 8024
spruce - Version 1.19.1
jq-1.6
```

Followed steps in readme
```
git clone https://github.com/cloudfoundry-community/bosh-deployment-visualizer ~/workspace/bosh-deployment-visualizer
git clone https://github.com/cloudfoundry/cf-deployment ~/workspace/cf-deployment
~/workspace/bosh-deployment-visualizer/visualize.sh ~/workspace/cf-deployment/cf-deployment.yml
```

Are you able to provide the versions you have used?

**Comment by rkoster** [comment]
could you retry with master, since I fixed an issue when az's contain `-` in their name: https://github.com/cloudfoundry-community/bosh-deployment-visualizer/commit/9084504b941b4c353cdc8b5beb53f23069b2fa6c

**Comment by shreddedbacon** [comment]
Still getting the same image generated at the end.
What version of PlantUML are you using?

When I export just the UML into https://liveuml.com/ it renders somewhat correctly there, no joining lines though.

**Comment by shreddedbacon** [comment]
I managed to get this to work.

I had to download the PlantUML version from http://sourceforge.net/projects/plantuml/files/plantuml.jar/download which matches the version in brew

Copied the packaged version script into a new plantuml executable script as below and put that in my $PATH somewhere
```
#!/bin/sh
if [ -n "${JAVA_HOME}" ] && [ -x "${JAVA_HOME}/bin/java" ] ; then
    JAVA="${JAVA_HOME}/bin/java"
elif [ -x /usr/bin/java ] ; then
    JAVA=/usr/bin/java
else
    echo Cannot find JVM
    exit 1
fi
# reference location where new plantuml.jar lives
$JAVA -jar $HOME/bin/plantuml.jar ${@
```
I also had to install graphviz too.
```
sudo apt install graphviz
```

Hopefully this helps someone else.
